spring.application.name=HackthonSeal


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/hackathonseal
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=QBjpvywLlWAFYOqvFXkK00nc4LL36DPy3ZofTST3kv7
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000
